apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-fcgi-params
data:
  SCRIPT_FILENAME: "/var/www/html/public/index.php"


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/use-proxy-protocol: "true"
    nginx.ingress.kubernetes.io/real-ip-header: "proxy_protocol"
    nginx.ingress.kubernetes.io/proxy-real-ip-cidr: "0.0.0.0/0"
    nginx.ingress.kubernetes.io/backend-protocol: "FCGI"
    nginx.ingress.kubernetes.io/fastcgi-index: "index.php"
    nginx.ingress.kubernetes.io/fastcgi-params-configmap: "laravel-fcgi-params"
    # Add Laravel-specific optimizations
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~ /\.(?!well-known).* {
          deny all;
      }
      location = /favicon.ico { access_log off; log_not_found off; }
      location = /robots.txt  { access_log off; log_not_found off; }
spec:
  rules:
    - host: {{ .Values.app.env.APP_URL | trimPrefix "https://" | trimPrefix "http://" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-service
                port:
                  name: http


